Repository pie-sfac/1-16-careMango, pull requests merged in 2023-07, with the labels that each got.

#15 14 common components 생성 (Mark up+Styling+일부 기능 구현) + eslint 수정
  .eslintrc.json
  package-lock.json
  src/App.tsx
  src/atoms/commonAtom.ts
  src/components/common/inputContact.tsx
  src/components/common/inputMemo.tsx
  src/components/common/inputName.tsx
  src/components/common/selectDate.tsx
  src/components/common/selectInstructor.tsx
  src/components/common/selectTime.tsx
Labels: enhancement

#18 17 16 eslint error fix
  .eslintrc.json
  package-lock.json
  package.json
  postcss.config.js
  tailwind.config.js
  vite.config.ts
Labels: bug, help wanted, wontfix

#20 19 common components 수정 (title을 props로 받아오기) + eslint 수정
  .eslintrc.json
  src/App.tsx
  src/atoms/commonAtom.ts
  src/components/common/inputContact.tsx
  src/components/common/inputMemo.tsx
  src/components/common/inputName.tsx
  src/components/common/selectDate.tsx
  src/components/common/selectInstructor.tsx
  src/components/common/selectTime.tsx
Labels: enhancement, lint

#25 24 react router dom
  package-lock.json
  package.json
  src/App.tsx
Labels: enhancement

#27 26 Title custom class 추가
  src/index.css
Labels: CSS3

#28 10 일정조회-상담생성 페이지 Mark up+Styling+일부 기능 구현
  src/App.tsx
  src/routes/counseling/createCounseling.tsx
Labels: enhancement, HTML5, CSS3

#32 31 components 파일명 PascalCase로 변경
  src/components/common/InputContact.tsx
  src/components/common/InputMemo.tsx
  src/components/common/InputName.tsx
  src/components/common/SelectDate.tsx
  src/components/common/SelectInstructor.tsx
  src/components/common/SelectTime.tsx
Labels: documentation

#33 2 log in (in working)
  .eslintrc.json
  index.html
  package-lock.json
  package.json
  public/team16.png
  public/vite.svg
  src/App.tsx
  src/main.tsx
  src/routes/login.tsx
Labels: bug, enhancement, HTML5, lint

#39 38 Modal 설치
  package-lock.json
  package.json
Labels: enhancement

#40 23 check schedule
  public/data/scheduleData.json
  src/components/common/Card.tsx
  src/index.css
  src/routes/checkSchedule.tsx
Labels: enhancement, CSS3

#41 34 일정관리-상담-일정 상세조회 페이지 Markup+Styling+Mocking+Modal
  public/data/counselingData.json
  src/App.tsx
  src/atoms/counselingAtom.ts
  src/components/counseling/CounselingModal.tsx
  src/routes/counseling/checkCounseling.tsx
  src/routes/counseling/createCounseling.tsx
Labels: enhancement, HTML5, CSS3

#53 37 로그인 페이지 스타일링 기능
  src/App.tsx
  src/routes/login.tsx
Labels: enhancement

#59 57 공통 컴포넌트 recoil 말고 useState로 변경
  src/App.tsx
  src/components/common/InputContact.tsx
  src/components/common/InputMemo.tsx
  src/components/common/InputName.tsx
  src/components/common/SelectDate.tsx
  src/components/common/SelectInstructor.tsx
  src/components/common/SelectTime.tsx
Labels: enhancement

#61 Feat: 상담 일정 생성/조회 페이지 recoil 말고 useState 적용, 컴포넌트 분리 및 적용
  src/App.tsx
  src/atoms/commonAtom.ts
  src/atoms/counselingAtom.ts
  src/components/counseling/CounselingModal.tsx
  src/components/counseling/CounselingScheduleBox.tsx
  src/components/counseling/CounselingScheduleDetail.tsx
  src/routes/counseling/checkCounseling.tsx
  src/routes/counseling/createCounseling.tsx
  src/types/counselingSchedule.ts
Labels: enhancement, HTML5

#60 Feat: 일정변경-개인수업 페이지 생성 및 라우터 적용
  .eslintrc.json
  src/App.tsx
  src/components/common/SelectDate.tsx
  src/components/common/SelectInstructor.tsx
  src/components/common/SelectTime.tsx
  src/routes/changeSchedule.tsx
  src/routes/checkSchedule.tsx
  src/utils/apiInstance.ts
  tsconfig.json
Labels: enhancement, HTML5, CSS3

#69 67 일정관리-상담-일정 생성/상세조회 페이지 수정
  src/App.tsx
  src/components/common/InputContact.tsx
  src/components/common/InputMemo.tsx
  src/components/common/InputName.tsx
  src/components/common/SelectCounselor.tsx
  src/components/common/SelectDate.tsx
  src/components/common/SelectTime.tsx
  src/routes/counseling/checkCounseling.tsx
  src/routes/counseling/createCounseling.tsx
Labels: bug, HTML5

#71 68 회원관리 메인/회원생성 페이지 생성
  public/data/membersData.json
  src/App.tsx
  src/atoms/members/membersAtom.ts
  src/components/common/InputBirth.tsx
  src/components/common/SelectJob.tsx
  src/components/common/SelectSex.tsx
  src/components/common/SelectVisitRoute.tsx
  src/components/members/AgreeCondition.tsx
  src/routes/counseling/checkCounseling.tsx
  src/routes/counseling/createCounseling.tsx
  src/routes/members/createMembers.tsx
  src/routes/members/showMembers.tsx
  src/types/counselingSchedule.ts
  src/types/members.ts
Labels: enhancement, HTML5, CSS3

#74 62 main
  public/images/Banners.png
  src/routes/login.tsx
  src/routes/main.tsx
Labels: enhancement, HTML5, CSS3

#76 73 회원 관리 페이지 api 연동 테스트
  src/atoms/members/membersAtom.ts
  src/components/common/InputBirth.tsx
  src/components/common/InputContact.tsx
  src/components/common/InputMemo.tsx
  src/components/common/InputName.tsx
  src/components/common/SelectDate.tsx
  src/components/common/SelectJob.tsx
  src/components/common/SelectSex.tsx
  src/components/common/SelectTime.tsx
  src/components/common/SelectVisitRoute.tsx
  src/components/counseling/CounselingScheduleBox.tsx
  src/components/counseling/CounselingScheduleDetail.tsx
  src/components/members/AgreeCondition.tsx
  src/components/members/MembersItem.tsx
  src/components/members/NoMembers.tsx
  src/routes/counseling/checkCounseling.tsx
  src/routes/members/createMembers.tsx
  src/routes/members/showMembers.tsx
  src/types/counseling/counselingSchedule.ts
  src/types/members/members.ts
Labels: bug, enhancement, HTML5, CSS3

#79 77 회원 생성 시 성별, 날짜 부분 입력 값 수정
  src/components/common/InputBirth.tsx
  src/components/common/SelectSex.tsx
  src/routes/members/showMembers.tsx
  src/types/members/members.ts
Labels: bug
